(()=>{
const cfg=window.SUPABASE_CONFIG||{};const db=window.supabase?.createClient(cfg.url,cfg.anonKey);window.academyDB=db;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=new URLSearchParams(location.search);const page=document.body.dataset.page;
async function session(){const r=await db.auth.getSession();if(!r.data.session){location.href=location.pathname.includes('/teacher/')?'../portal-login.html':location.pathname.includes('/student/')?'../portal-login.html':'login.html';return null}return r.data.session}
async function profile(uid){const r=await db.from('profiles').select('*').eq('id',uid).single();return r.data}
async function guard(role){const s=await session();if(!s)return;const p=await profile(s.user.id);if(!p||p.role!==role){location.href=role==='admin'?'../portal-login.html':'../portal-login.html';return}document.querySelectorAll('[data-name]').forEach(x=>x.textContent=p.full_name||s.user.email);return {s,p}}
window.portalLogout=async()=>{await db.auth.signOut();location.href=page==='admin'?'login.html':'../portal-login.html'};
const set=(id,v)=>{const e=document.getElementById(id);if(e)e.innerHTML=v};
function rowEmpty(cols,msg='No records found.') {return `<tr><td colspan="${cols}" class="empty">${esc(msg)}</td></tr>`}
async function teacherData(){const g=await guard('teacher');if(!g)return;const uid=g.s.user.id;const today=new Date().toISOString().slice(0,10);if(page==='teacher-dashboard'||page==='teacher-classes'||page==='teacher-schedule'||page==='teacher-attendance'){const r=await db.from('class_schedule').select('*,courses(title),student:profiles!class_schedule_student_id_fkey(full_name)').eq('teacher_id',uid).order('class_date',{ascending:true}).order('start_time',{ascending:true});const data=r.data||[];set('todayCount',data.filter(x=>x.class_date===today).length);set('scheduledCount',data.filter(x=>x.status==='scheduled').length);set('completedCount',data.filter(x=>x.status==='completed').length);set('studentCount',new Set(data.map(x=>x.student_id)).size);set('classRows',data.map(x=>`<tr><td>${esc(x.class_date)}</td><td>${esc(x.start_time||'')} ${x.end_time?'– '+esc(x.end_time):''}</td><td>${esc(x.student?.full_name||x.student_id)}</td><td>${esc(x.courses?.title||'')}</td><td><span class="pill">${esc(x.status)}</span></td><td>${x.meeting_link?`<a class="btn-small" target="_blank" href="${esc(x.meeting_link)}">Join</a>`:'—'}</td><td><select onchange="markAttendance('${x.id}','${x.student_id}',this.value)"><option value="">Mark</option><option>present</option><option>absent</option><option>late</option></select></td><td><button class="btn-small" onclick="changeClass('${x.id}','active')">Start</button> <button class="btn-small" onclick="changeClass('${x.id}','completed')">Complete</button></td></tr>`).join('')||rowEmpty(8));}
if(page==='teacher-students'){const r=await db.from('class_schedule').select('student_id,student:profiles!class_schedule_student_id_fkey(id,full_name,email)').eq('teacher_id',uid);const m=new Map((r.data||[]).map(x=>[x.student_id,x.student]));set('studentRows',[...m.values()].map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.email||'')}</td><td>${esc(x.id)}</td></tr>`).join('')||rowEmpty(3))}
if(page==='teacher-courses'){const r=await db.from('student_enrollments').select('course_id,courses(id,title,description)').eq('teacher_id',uid);const m=new Map((r.data||[]).map(x=>[x.course_id,x.courses]));set('courseRows',[...m.values()].map(x=>`<tr><td>${esc(x?.title)}</td><td>${esc(x?.description||'')}</td></tr>`).join('')||rowEmpty(2))}
if(page==='teacher-leaves'){const r=await db.from('leaves').select('*').eq('user_id',uid).order('created_at',{ascending:false});set('leaveRows',(r.data||[]).map(x=>`<tr><td>${esc(x.start_date)}</td><td>${esc(x.end_date)}</td><td>${esc(x.reason)}</td><td><span class="pill">${esc(x.status)}</span></td></tr>`).join('')||rowEmpty(4));document.getElementById('leaveForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await db.from('leaves').insert({user_id:uid,role:'teacher',start_date:f.get('start_date'),end_date:f.get('end_date'),reason:f.get('reason')});if(r.error)alert(r.error.message);else location.reload()})}
if(page==='teacher-salary'){const r=await db.from('teacher_salaries').select('*').eq('teacher_id',uid).order('salary_month',{ascending:false});set('salaryRows',(r.data||[]).map(x=>`<tr><td>${esc(x.salary_month)}</td><td>${esc(x.amount)} ${esc(x.currency)}</td><td><span class="pill">${esc(x.status)}</span></td><td>${esc(x.paid_at||'')}</td></tr>`).join('')||rowEmpty(4))}
if(page==='teacher-profile'){set('profileName',esc(g.p.full_name||''));set('profileEmail',esc(g.s.user.email||''));document.getElementById('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await db.rpc('update_my_profile',{p_full_name:f.get('full_name')});if(r.error)alert(r.error.message);else alert('Profile updated.')})}
}
window.markAttendance=async(id,student,status)=>{if(!status)return;const g=await guard('teacher');if(!g)return;const r=await db.from('attendance').upsert({schedule_id:id,student_id:student,teacher_id:g.s.user.id,status},{onConflict:'schedule_id,student_id'});if(r.error)alert(r.error.message)};
window.changeClass=async(id,status)=>{const g=await guard('teacher');if(!g)return;const r=await db.from('class_schedule').update({status}).eq('id',id).eq('teacher_id',g.s.user.id);if(r.error)alert(r.error.message);else location.reload()};
async function studentData(){const g=await guard('student');if(!g)return;const uid=g.s.user.id;if(page==='student-dashboard'||page==='student-schedule'||page==='student-classes'){const [e,s,a,p,n,c]=await Promise.all([db.from('student_enrollments').select('*,courses(title)').eq('student_id',uid),db.from('class_schedule').select('*,courses(title),teacher:profiles!class_schedule_teacher_id_fkey(full_name)').eq('student_id',uid).order('class_date').order('start_time'),db.from('attendance').select('status').eq('student_id',uid),db.from('student_payments').select('*').eq('student_id',uid).order('created_at',{ascending:false}),db.from('notifications').select('*').eq('user_id',uid).order('created_at',{ascending:false}),db.from('certificates').select('*,courses(title)').eq('student_id',uid)]);set('courseCount',e.data?.length||0);set('classCount',(s.data||[]).filter(x=>x.status==='scheduled').length);set('attendanceRate',a.data?.length?Math.round(a.data.filter(x=>x.status==='present').length/a.data.length*100)+'%':'—');set('paymentRows',(p.data||[]).map(x=>`<tr><td>${esc(x.amount)} ${esc(x.currency||'')}</td><td>${esc(x.method)}</td><td>${esc(x.status)}</td><td>${esc(x.created_at?.slice(0,10))}</td></tr>`).join('')||rowEmpty(4));set('scheduleRows',(s.data||[]).map(x=>`<tr><td>${esc(x.class_date)}</td><td>${esc(x.start_time||'')}</td><td>${esc(x.courses?.title||'')}</td><td>${esc(x.teacher?.full_name||'')}</td><td>${x.meeting_link?`<a class="btn-small" target="_blank" href="${esc(x.meeting_link)}">Join</a>`:'—'}</td><td>${esc(x.status)}</td></tr>`).join('')||rowEmpty(6));set('courseRows',(e.data||[]).map(x=>`<tr><td>${esc(x.courses?.title||'')}</td><td>${esc(x.status)}</td><td>${x.progress||0}%</td></tr>`).join('')||rowEmpty(3));set('notificationRows',(n.data||[]).map(x=>`<div class="card"><b>${esc(x.title)}</b><p>${esc(x.body)}</p></div>`).join('')||'<p class="empty">No notifications.</p>');set('certRows',(c.data||[]).map(x=>`<tr><td>${esc(x.courses?.title||'')}</td><td>${esc(x.certificate_no||'')}</td><td>${esc(x.issued_at||'')}</td></tr>`).join('')||rowEmpty(3))}
if(page==='student-teacher'){const r=await db.from('class_schedule').select('class_date,courses(title),teacher:profiles!class_schedule_teacher_id_fkey(full_name),meeting_link').eq('student_id',uid).order('class_date',{ascending:true});set('scheduleRows',(r.data||[]).map(x=>`<tr><td>${esc(x.class_date)}</td><td>${esc(x.courses?.title||'')}</td><td>${esc(x.teacher?.full_name||'')}</td><td>${x.meeting_link?`<a class=\"btn-small\" target=\"_blank\" href=\"${esc(x.meeting_link)}\">Join</a>`:'—'}</td></tr>`).join('')||rowEmpty(4))}
if(page==='student-attendance'){const r=await db.from('attendance').select('*,class_schedule(class_date,start_time,end_time,courses(title))').eq('student_id',uid).order('created_at',{ascending:false});set('attendanceRows',(r.data||[]).map(x=>`<tr><td>${esc(x.class_schedule?.class_date||'')}</td><td>${esc(x.status)}</td><td>${esc(x.notes||'')}</td></tr>`).join('')||rowEmpty(3))}
if(page==='student-fees'){const r=await db.from('student_payments').select('*').eq('student_id',uid).order('created_at',{ascending:false});set('paymentRows',(r.data||[]).map(x=>`<tr><td>${esc(x.amount)} ${esc(x.currency||'')}</td><td>${esc(x.method)}</td><td>${esc(x.status)}</td><td>${esc(x.reference||'')}</td><td>${esc(x.created_at?.slice(0,10))}</td></tr>`).join('')||rowEmpty(5))}
if(page==='student-leaves'){const r=await db.from('leaves').select('*').eq('user_id',uid).order('created_at',{ascending:false});set('leaveRows',(r.data||[]).map(x=>`<tr><td>${esc(x.start_date)}</td><td>${esc(x.end_date)}</td><td>${esc(x.reason)}</td><td>${esc(x.status)}</td></tr>`).join('')||rowEmpty(4));document.getElementById('leaveForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await db.from('leaves').insert({user_id:uid,role:'student',start_date:f.get('start_date'),end_date:f.get('end_date'),reason:f.get('reason')});if(r.error)alert(r.error.message);else location.reload()})}
if(page==='student-profile'){set('profileName',esc(g.p.full_name||''));set('profileEmail',esc(g.s.user.email||''));document.getElementById('profileForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await db.rpc('update_my_profile',{p_full_name:f.get('full_name')});if(r.error)alert(r.error.message);else alert('Profile updated.')})}
}
if(page?.startsWith('teacher-'))teacherData();if(page?.startsWith('student-'))studentData();
})();